import Head from "next/head";
import Link from "next/link";
import DataTable from "~/components/Datatable";
import UploadButton from "~/components/UploadButton";
import { api } from "~/utils/api";
import { useAuth, useUser } from '@clerk/nextjs';
import { useEffect } from 'react';
import { useRouter } from 'next/router';

export default function Home() {

  const { isSignedIn } = useAuth();
  const { user } = useUser()
  const router = useRouter();

  
  useEffect(() => {
    if (!isSignedIn) {
      void router.push('/login'); // Redirect to sign-in page if not signed in
    }
  }, [isSignedIn, router]);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {user && <h1>Welcome, {user.firstName} {user.lastName}!</h1>} {/* Display user name */}

      <UploadButton/>
      <DataTable/>

    </>
  );
}
